{% set name = "eklipse" %}
{% set version = "1.8" %}
{% set sha256 = "cb2089c9b1d42bfab2b26b794a148b109d1ecb5d86b5f60adf3c8f93b01affee" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/dooguypapua/eKLIPse/archive/refs/heads/master.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python

requirements:
  build:
     - curl
     - unzip
  host:
    - openjdk >=8
    - python =2.7
    - biopython
    - tqdm
    - samtools
    - blastn >=2.3.0+
    - circos
  run:
    - openjdk >=8
    - python =2.7
    - biopython
    - tqdm
    - samtools
    - blastn >=2.3.0+
    - circos

test:
  commands:
    - python eKLIPse.py --help

about:
  home: https://github.com/dooguypapua/eKLIPse
  license: GNU General Public v3 or later (GPLv3+)
  license_family: GPL3
  license_file: LICENSE
  summary: "eKLIPse is a sensitive and specific tool allowing the detection and quantification of large mtDNA rearrangements."